// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// sops.cpp
doubles cpp_markov_propagate(doubles_matrix<> initial, list transitions, integers non_absorb, integers absorb);
extern "C" SEXP _mostr_cpp_markov_propagate(SEXP initial, SEXP transitions, SEXP non_absorb, SEXP absorb) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_markov_propagate(cpp11::as_cpp<cpp11::decay_t<doubles_matrix<>>>(initial), cpp11::as_cpp<cpp11::decay_t<list>>(transitions), cpp11::as_cpp<cpp11::decay_t<integers>>(non_absorb), cpp11::as_cpp<cpp11::decay_t<integers>>(absorb)));
  END_CPP11
}
// sops.cpp
doubles cpp_markov_update_logits(doubles_matrix<> previous, doubles_matrix<> logits, integers non_absorb, integers absorb);
extern "C" SEXP _mostr_cpp_markov_update_logits(SEXP previous, SEXP logits, SEXP non_absorb, SEXP absorb) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_markov_update_logits(cpp11::as_cpp<cpp11::decay_t<doubles_matrix<>>>(previous), cpp11::as_cpp<cpp11::decay_t<doubles_matrix<>>>(logits), cpp11::as_cpp<cpp11::decay_t<integers>>(non_absorb), cpp11::as_cpp<cpp11::decay_t<integers>>(absorb)));
  END_CPP11
}
// sops.cpp
doubles cpp_markov_update_po(doubles_matrix<> previous, doubles scalar_predictor, doubles cutpoints, integers non_absorb, integers absorb);
extern "C" SEXP _mostr_cpp_markov_update_po(SEXP previous, SEXP scalar_predictor, SEXP cutpoints, SEXP non_absorb, SEXP absorb) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_markov_update_po(cpp11::as_cpp<cpp11::decay_t<doubles_matrix<>>>(previous), cpp11::as_cpp<cpp11::decay_t<doubles>>(scalar_predictor), cpp11::as_cpp<cpp11::decay_t<doubles>>(cutpoints), cpp11::as_cpp<cpp11::decay_t<integers>>(non_absorb), cpp11::as_cpp<cpp11::decay_t<integers>>(absorb)));
  END_CPP11
}
// sops.cpp
list cpp_run_sop_delta(doubles_matrix<> initial_design, list transition_designs, doubles_matrix<> gamma, doubles_matrix<> coefficient_map, integers origin_positions, integers non_absorb, integers absorb, int intercept, int group_size, bool retain_individual_probabilities);
extern "C" SEXP _mostr_cpp_run_sop_delta(SEXP initial_design, SEXP transition_designs, SEXP gamma, SEXP coefficient_map, SEXP origin_positions, SEXP non_absorb, SEXP absorb, SEXP intercept, SEXP group_size, SEXP retain_individual_probabilities) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_run_sop_delta(cpp11::as_cpp<cpp11::decay_t<doubles_matrix<>>>(initial_design), cpp11::as_cpp<cpp11::decay_t<list>>(transition_designs), cpp11::as_cpp<cpp11::decay_t<doubles_matrix<>>>(gamma), cpp11::as_cpp<cpp11::decay_t<doubles_matrix<>>>(coefficient_map), cpp11::as_cpp<cpp11::decay_t<integers>>(origin_positions), cpp11::as_cpp<cpp11::decay_t<integers>>(non_absorb), cpp11::as_cpp<cpp11::decay_t<integers>>(absorb), cpp11::as_cpp<cpp11::decay_t<int>>(intercept), cpp11::as_cpp<cpp11::decay_t<int>>(group_size), cpp11::as_cpp<cpp11::decay_t<bool>>(retain_individual_probabilities)));
  END_CPP11
}
// sops.cpp
integers cpp_sample_categorical_rows(doubles_matrix<> probabilities);
extern "C" SEXP _mostr_cpp_sample_categorical_rows(SEXP probabilities) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_sample_categorical_rows(cpp11::as_cpp<cpp11::decay_t<doubles_matrix<>>>(probabilities)));
  END_CPP11
}
// sops.cpp
doubles cpp_normalize_probability_array(doubles values, int draws, int observations, int states);
extern "C" SEXP _mostr_cpp_normalize_probability_array(SEXP values, SEXP draws, SEXP observations, SEXP states) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_normalize_probability_array(cpp11::as_cpp<cpp11::decay_t<doubles>>(values), cpp11::as_cpp<cpp11::decay_t<int>>(draws), cpp11::as_cpp<cpp11::decay_t<int>>(observations), cpp11::as_cpp<cpp11::decay_t<int>>(states)));
  END_CPP11
}
// sops.cpp
doubles cpp_reduce_sops_draws(doubles values, int draws, int observations, int times, int states, integers groups, int group_count);
extern "C" SEXP _mostr_cpp_reduce_sops_draws(SEXP values, SEXP draws, SEXP observations, SEXP times, SEXP states, SEXP groups, SEXP group_count) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_reduce_sops_draws(cpp11::as_cpp<cpp11::decay_t<doubles>>(values), cpp11::as_cpp<cpp11::decay_t<int>>(draws), cpp11::as_cpp<cpp11::decay_t<int>>(observations), cpp11::as_cpp<cpp11::decay_t<int>>(times), cpp11::as_cpp<cpp11::decay_t<int>>(states), cpp11::as_cpp<cpp11::decay_t<integers>>(groups), cpp11::as_cpp<cpp11::decay_t<int>>(group_count)));
  END_CPP11
}
// sops.cpp
doubles cpp_markov_update_draws(doubles previous, doubles transition, int draws, int observations, int states, integers non_absorb, integers absorb);
extern "C" SEXP _mostr_cpp_markov_update_draws(SEXP previous, SEXP transition, SEXP draws, SEXP observations, SEXP states, SEXP non_absorb, SEXP absorb) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_markov_update_draws(cpp11::as_cpp<cpp11::decay_t<doubles>>(previous), cpp11::as_cpp<cpp11::decay_t<doubles>>(transition), cpp11::as_cpp<cpp11::decay_t<int>>(draws), cpp11::as_cpp<cpp11::decay_t<int>>(observations), cpp11::as_cpp<cpp11::decay_t<int>>(states), cpp11::as_cpp<cpp11::decay_t<integers>>(non_absorb), cpp11::as_cpp<cpp11::decay_t<integers>>(absorb)));
  END_CPP11
}
// sops.cpp
doubles cpp_markov_update_second_order(doubles previous, doubles transition, int observations, int states, integers older, integers current, integers absorb);
extern "C" SEXP _mostr_cpp_markov_update_second_order(SEXP previous, SEXP transition, SEXP observations, SEXP states, SEXP older, SEXP current, SEXP absorb) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_markov_update_second_order(cpp11::as_cpp<cpp11::decay_t<doubles>>(previous), cpp11::as_cpp<cpp11::decay_t<doubles>>(transition), cpp11::as_cpp<cpp11::decay_t<int>>(observations), cpp11::as_cpp<cpp11::decay_t<int>>(states), cpp11::as_cpp<cpp11::decay_t<integers>>(older), cpp11::as_cpp<cpp11::decay_t<integers>>(current), cpp11::as_cpp<cpp11::decay_t<integers>>(absorb)));
  END_CPP11
}
// sops.cpp
doubles cpp_blrm_probabilities(doubles base_eta, doubles intercepts, doubles threshold_eta, doubles threshold_scale, int draws, int observations, int thresholds);
extern "C" SEXP _mostr_cpp_blrm_probabilities(SEXP base_eta, SEXP intercepts, SEXP threshold_eta, SEXP threshold_scale, SEXP draws, SEXP observations, SEXP thresholds) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_blrm_probabilities(cpp11::as_cpp<cpp11::decay_t<doubles>>(base_eta), cpp11::as_cpp<cpp11::decay_t<doubles>>(intercepts), cpp11::as_cpp<cpp11::decay_t<doubles>>(threshold_eta), cpp11::as_cpp<cpp11::decay_t<doubles>>(threshold_scale), cpp11::as_cpp<cpp11::decay_t<int>>(draws), cpp11::as_cpp<cpp11::decay_t<int>>(observations), cpp11::as_cpp<cpp11::decay_t<int>>(thresholds)));
  END_CPP11
}
// sops.cpp
doubles cpp_markov_update_second_order_po(doubles previous, doubles scalar_predictor, doubles cutpoints, int observations, int states, integers older, integers current, integers absorb);
extern "C" SEXP _mostr_cpp_markov_update_second_order_po(SEXP previous, SEXP scalar_predictor, SEXP cutpoints, SEXP observations, SEXP states, SEXP older, SEXP current, SEXP absorb) {
  BEGIN_CPP11
    return cpp11::as_sexp(cpp_markov_update_second_order_po(cpp11::as_cpp<cpp11::decay_t<doubles>>(previous), cpp11::as_cpp<cpp11::decay_t<doubles>>(scalar_predictor), cpp11::as_cpp<cpp11::decay_t<doubles>>(cutpoints), cpp11::as_cpp<cpp11::decay_t<int>>(observations), cpp11::as_cpp<cpp11::decay_t<int>>(states), cpp11::as_cpp<cpp11::decay_t<integers>>(older), cpp11::as_cpp<cpp11::decay_t<integers>>(current), cpp11::as_cpp<cpp11::decay_t<integers>>(absorb)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_mostr_cpp_blrm_probabilities",            (DL_FUNC) &_mostr_cpp_blrm_probabilities,             7},
    {"_mostr_cpp_markov_propagate",              (DL_FUNC) &_mostr_cpp_markov_propagate,               4},
    {"_mostr_cpp_markov_update_draws",           (DL_FUNC) &_mostr_cpp_markov_update_draws,            7},
    {"_mostr_cpp_markov_update_logits",          (DL_FUNC) &_mostr_cpp_markov_update_logits,           4},
    {"_mostr_cpp_markov_update_po",              (DL_FUNC) &_mostr_cpp_markov_update_po,               5},
    {"_mostr_cpp_markov_update_second_order",    (DL_FUNC) &_mostr_cpp_markov_update_second_order,     7},
    {"_mostr_cpp_markov_update_second_order_po", (DL_FUNC) &_mostr_cpp_markov_update_second_order_po,  8},
    {"_mostr_cpp_normalize_probability_array",   (DL_FUNC) &_mostr_cpp_normalize_probability_array,    4},
    {"_mostr_cpp_reduce_sops_draws",             (DL_FUNC) &_mostr_cpp_reduce_sops_draws,              7},
    {"_mostr_cpp_run_sop_delta",                 (DL_FUNC) &_mostr_cpp_run_sop_delta,                 10},
    {"_mostr_cpp_sample_categorical_rows",       (DL_FUNC) &_mostr_cpp_sample_categorical_rows,        1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_mostr(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
