# Generated by cpp11: do not edit by hand

cpp_markov_propagate <- function(initial, transitions, non_absorb, absorb) {
  .Call(`_mostr_cpp_markov_propagate`, initial, transitions, non_absorb, absorb)
}

cpp_markov_update_logits <- function(previous, logits, non_absorb, absorb) {
  .Call(`_mostr_cpp_markov_update_logits`, previous, logits, non_absorb, absorb)
}

cpp_markov_update_po <- function(previous, scalar_predictor, cutpoints, non_absorb, absorb) {
  .Call(`_mostr_cpp_markov_update_po`, previous, scalar_predictor, cutpoints, non_absorb, absorb)
}

cpp_run_sop_delta <- function(initial_design, transition_designs, gamma, coefficient_map, origin_positions, non_absorb, absorb, intercept, group_size, retain_individual_probabilities) {
  .Call(`_mostr_cpp_run_sop_delta`, initial_design, transition_designs, gamma, coefficient_map, origin_positions, non_absorb, absorb, intercept, group_size, retain_individual_probabilities)
}

cpp_sample_categorical_rows <- function(probabilities) {
  .Call(`_mostr_cpp_sample_categorical_rows`, probabilities)
}

cpp_normalize_probability_array <- function(values, draws, observations, states) {
  .Call(`_mostr_cpp_normalize_probability_array`, values, draws, observations, states)
}

cpp_reduce_sops_draws <- function(values, draws, observations, times, states, groups, group_count) {
  .Call(`_mostr_cpp_reduce_sops_draws`, values, draws, observations, times, states, groups, group_count)
}

cpp_markov_update_draws <- function(previous, transition, draws, observations, states, non_absorb, absorb) {
  .Call(`_mostr_cpp_markov_update_draws`, previous, transition, draws, observations, states, non_absorb, absorb)
}

cpp_markov_update_second_order <- function(previous, transition, observations, states, older, current, absorb) {
  .Call(`_mostr_cpp_markov_update_second_order`, previous, transition, observations, states, older, current, absorb)
}

cpp_blrm_probabilities <- function(base_eta, intercepts, threshold_eta, threshold_scale, draws, observations, thresholds) {
  .Call(`_mostr_cpp_blrm_probabilities`, base_eta, intercepts, threshold_eta, threshold_scale, draws, observations, thresholds)
}

cpp_markov_update_second_order_po <- function(previous, scalar_predictor, cutpoints, observations, states, older, current, absorb) {
  .Call(`_mostr_cpp_markov_update_second_order_po`, previous, scalar_predictor, cutpoints, observations, states, older, current, absorb)
}
